<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Api_Presentacion</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aplicacion\Aplicacion.csproj" />
    <ProjectReference Include="..\Domain\Dominio.csproj" />
    <ProjectReference Include="..\Infraestructura\Infraestructura.csproj" />
  </ItemGroup>

</Project>
